name: Publish docker images

on:
  schedule:
    - cron: '0 0 * * 1' # each Monday 12:00 UTC
  push:
    branches: [ master ]
    tags: [ 'v*.*.*' ] # semver release
  pull_request:
    branches: [ master ]

env:
  REGISTRY: ghcr.io
  USERNAME: ${{ github.actor }}
  PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  DOCKER_REPOSITORY_OWNER: ${{github.repository_owner}}
  IMAGE: esp-v2

jobs:

  build-esp-v2:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Log into registry ${{ env.REGISTRY }}
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ env.USERNAME }}
        password: ${{ env.PASSWORD }}
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.DOCKER_REPOSITORY_OWNER }}/${{ env.IMAGE }}
        tags: |
          type=ref,event=branch
          type=ref,event=tag
          type=schedule,pattern=nightly
          type=raw,latest
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: ""
